# Customize below to fit your system

# paths
PREFIX = /usr/share
WWWPREFIX = /var/www
GPIGEON_DIR = $(PREFIX)/gpigeon
WWWDIR = $(WWWPREFIX)/gpigeon
COOKIES_DIR = $(GPIGEON_DIR)/cookies
UPLOAD_TMPDIR = $(GPIGEON_DIR)/tmp
LINK_TEMPLATE_PATH = $(GPIGEON_DIR)/link-tmpl.cgi
_GPG_HOMEDIR = $(GPIGEON_DIR)/gnupg
GPIGEON_PATH = $(WWWDIR)/cgi-bin/gpigeon.cgi

# system stuff
WWWUSER=www-data #it must match up with your nginx user. For ex. on arch it's 'http'
WWWGROUP=www-data # in general same as WWWUSER

# form customization stuff
MSG_FORM_CHAR_LIMIT = 3000
MAX_MB_LIMIT = 100

# argon2id hash. generated by genpass.pl if empty when running make
ARGON2ID_HASH =

# email related
HAS_MAILSERVER = 0# choose 0 if you'll use an external mail server, 1 if local mail server installed.
MYMAIL_ADDR =# your mail address - required
MAILSENDER =# the mailer address that'll send you the encrypted mails - required
# you don't need to set the 3 last variables if you got a local mailserver.
MAILSENDER_PW =# password for the mailer address
SMTP_DOMAIN =# smtp domain pour the mailer
SMTP_PORT =# smtp port for the mailer

#optional, domain to generate nginx config for
#and where to put the config
WWWDOMAIN=
SITESENABLED=/etc/nginx/sites-enabled
